theme: jekyll-theme-cayman
title: Most Popular 90's Disney Album
description: The goal of this mini project was to find out: "Out of Tarzan, The Lion King, Hercules and The Little Mermaid; What is the Most Popular Album?"
